version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      target: runner  # Use the optimized "runner" stage
    container_name: localminds-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:password@mongodb:27017/nest?authSource=admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - ./logs:/app/logs  # Store logs persistently outside the container

volumes:
  mongo_data:
    driver: local
