version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      target: runner  # Use the optimized "runner" stage
    container_name: localminds-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://admin:password@mongodb:27017/nest?authSource=admin
      PORT: ${PORT}  # Injected by the cloud provider
      JWT_SECRET: ${JWT_SECRET}  # Injected by the cloud provider
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}  # Injected by the cloud provider
      MAIL_HOST: ${MAIL_HOST}  # Injected by the cloud provider
      MAIL_USER: ${MAIL_USER}  # Injected by the cloud provider
      GOOGLE_MAIL_APP_PASSWORD: ${GOOGLE_MAIL_APP_PASSWORD}  # Injected by the cloud provider
      MAIL_FROM: ${MAIL_FROM}  # Injected by the cloud provider
      FRONTEND_URL: ${FRONTEND_URL}  # Injected by the cloud provider
      PASSWORD_RESET_URL: ${PASSWORD_RESET_URL}  # Injected by the cloud provider
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}  # Injected by the cloud provider
      CORS_ORIGIN: ${CORS_ORIGIN}  # Injected by the cloud provider
      THROTTLE_TTL: ${THROTTLE_TTL}  # Injected by the cloud provider
      THROTTLE_LIMIT: ${THROTTLE_LIMIT}  # Injected by the cloud provider
      MOBILE_APP_SCHEME: ${MOBILE_APP_SCHEME}  # Injected by the cloud provider

    volumes:
      - ./logs:/app/logs  # Store logs persistently outside the container

volumes:
  mongo_data:
    driver: local