export enum ContactReasonType {
    GENERAL_INQUIRY = 'GENERAL_INQUIRY',
    BUG_REPORT = 'BUG_REPORT',
    FEATURE_REQUEST = 'FEATURE_REQUEST',
    ACCOUNT_ISSUE = 'ACCOUNT_ISSUE',
    SECURITY_CONCERN = 'SECURITY_CONCERN',
    BILLING_QUESTION = 'BILLING_QUESTION',
    OTHER = 'OTHER'
} 